title: Changeset

description: A lightweight CQRS/ES library

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker

show_downloads: false

github: [metadata]
#  repository_url: https://github.com/chgst
#  metadata: ~

google_analytics: UA-125572701-1

plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
